# Generated by Django 4.1.5 on 2023-01-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('nacimiento', models.DateField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ficha')),
            ],
        ),
    ]
